spring:
  profiles:
    active:
    - dev

---
server:
  port: 8900

spring:
  profiles: dev
  jpa:
    show-sql: true
api: 
  docs: enable

---
server:
  port: 8901

spring:
  profiles: test
  jpa:
    show-sql: true
api: 
  docs: enable
  
---
server:
  port: 8902

spring:
  profiles: prod 
  jpa:
    show-sql: false 

api: 
  docs: disable
 