server:
  port: 8088
  
#thymeleaf-springboot配置
spring:
  thymeleaf: #页面模板引擎
    cache: true #是否缓存，有缓存时会导致页面没法及时看到更新后的效果
    content-type: text/html; charset=utf-8
    enabled: true #是否启用
    encoding: UTF-8
    mode: HTML5
#    prefix: classpath:/templates/ #默认就是这个
    suffix: .html
   #static   （静态资源） 
  resources:
    add-mappings: true
    cache-period: 3600
#    static-locations:
#    - classpath:/static/ #默认就是这个
    chain:
      cache: true
      enabled: true
      gzipped: true
      html-application-cache: true

microservice: 
  url: http://localhost:8030
  system: /microservice-provider-web
  
  
      