spring:
  profiles:
    active:
    - dev

---
server:
  port: 8030

spring:
  profiles: dev

---
server:
  port: 8031

spring:
  profiles: test
  
---
server:
  port: 8032

spring:
  profiles: prod 
 