spring:
  profiles:
    active:
    - dev

---
server:
  port: 7700

spring:
  profiles: dev
  jpa:
    show-sql: true
api: 
  docs: enable

---
server:
  port: 7701

spring:
  profiles: test
  jpa:
    show-sql: true
api: 
  docs: enable
  
---
server:
  port: 7702

spring:
  profiles: prod 
  jpa:
    show-sql: false 

api: 
  docs: disable
 