spring:
  profiles:
    active:
    - dev

---
server:
  port: 8050

spring:
  profiles: dev
api: 
  docs: enable  

---
server:
  port: 8051

spring:
  profiles: test
  
---
server:
  port: 8052

spring:
  profiles: prod 
 