spring:
  profiles:
    active:
    - dev

---
server:
  port: 6800

spring:
  profiles: dev
  jpa:
    show-sql: true
api: 
  docs: enable
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


---
server:
  port: 6801

spring:
  profiles: test
  jpa:
    show-sql: true
api: 
  docs: enable
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
---
server:
  port: 6802

spring:
  profiles: prod 
  jpa:
    show-sql: false 

api: 
  docs: disable
 